### ISSUE TITLE
Generating REST client in VS2019 fails

### ISSUE THREAD

**Issue by omelhus** [Tripletex/tripletex-api2#12]
Hey friends,

I tried to create a new REST client using VS2019 (right click project -> add -> REST API Client), and unfortunately it fails with the following error message:

```
Exception: Property 'feeInvoiceText' in Model 'ProjectInvoiceDetails' is marked readOnly and is also required. This is not allowed.
```

I'm sure I'll manage to work my way around this, but thought you should know.

Cheers!

**Comment by jrtm** [comment]
Thank you! We have not seen this error before.

It looks like there are a few other fields marked both readOnly and required ("not null"), where this error would occur.

We have now created a test to automatically detect invalid combinations like this, and will get the existing ones fixed soon.

**Comment by jrtm** [comment]
The "soon" in my last comment was unfortunately a bit delayed due to the holidays, but everything should be fixed now. And the test to make sure we don't introduce any new invalid combinations is also in-place. 😃

**Comment by omelhus** [comment]
Thanks!
