### ISSUE TITLE
Issue while creating ledger voucher

### ISSUE THREAD

**Issue by pushpakssm** [Tripletex/tripletex-api2#15]
"validationMessages": [
    {
      "field": "postings",
      "message": "Et bilag kan ikke registreres uten posteringer.",
      "path": null,
      "rootId": null
    },
    {
      "field": "postings.row",
      "message": "Posteringene på rad 0 (guiRow 0) er systemgenererte og kan ikke opprettes eller endres på utsiden av Tripletex.",
      "path": null,
      "rootId": null
    }
  ]
The error I am getting while creating the posting, the data i am sending is as per example have in documentation. Please share if we have some small sample example for creating ledger voucher

**Comment by tlxtellef** [comment]
`row` is required when creating a voucher with postings. `row` can't be 0 as that value is used by the system. If 2 postings have matching `row` then the sum of those 2 has to be 0.

Some minimal example of using `POST /v2/ledger/voucher`

```
{
  "date": "2020-04-01",
  "description": "example",
  "postings": [
    {
      "row": 1,
      "amountGross": 1250,
      "amountGrossCurrency": 1250,
      "account": {
        "id": <a valid account id>
      }
    },
    {
      "row": 1,
      "amountGross": -1250,
      "amountGrossCurrency": -1250,
      "account": {
        "id": <a valid account id>
      }
    }
  ]
}
```

```
{
  "date": "2020-04-01",
  "description": "example",
  "postings": [
    {
      "row": 1,
      "amountGross": 1250,
      "amountGrossCurrency": 1250,
      "account": {
        "id": <a valid account id>
      }
    },
    {
      "row": 2,
      "amountGross": -1000,
      "amountGrossCurrency": -1000,
      "account": {
        "id": <a valid account id>
      }
    },
    {
      "row": 3,
      "amountGross": -250,
      "amountGrossCurrency": -250,
      "account": {
        "id": <a valid account id>
      }
    }
  ]
}
```
