### ISSUE TITLE
OutOfMemoryError when generatoring WorkingHoursScheme

### ISSUE THREAD

**Issue by tk-png** [Tripletex/tripletex-api2#20]
I'm trying to generate a Java client with the Swagger spec, but there is an issue when the the code generator tries to write the WorkingHoursScheme. If the computer trying to generate isn't powerful enough, the generator will throw an exception like this: 

96740 [ERROR] Java heap space -> [Help 1]
1125java.lang.OutOfMemoryError: Java heap space

I've tried with various versions of the OpenApi generator and the Swagger generator, and I will be able to generate everything only with certain versions, like OpenApi generator Maven plugin 4.2.0, but 4.3.x doesn't work. Sometimes it can help to increase memory but I think the problem should be better solved my adjusting WorkingHoursScheme.

**Comment by tlxtellef** [comment]
It is a problem with `swagger-codegen`, I already have an open issue with them regarding this. See [https://github.com/swagger-api/swagger-codegen/issues/10199](https://github.com/swagger-api/swagger-codegen/issues/10199) . To make it work for now you either need a 64Bit OS with at least 8GB of ram OR fork swagger-codegen and disable that pesky example generator.
