### ISSUE TITLE
Attaching a file to /order/{id}/:attach does not include filename

### ISSUE THREAD

**Issue by tadrian** [Tripletex/tripletex-api2#24]
Endpoint /order/{id}/:attach

Using the following method 
ResponseWrapperDocumentArchive respOrder = await oapi.AttachAsync(GetPDF(inv), orderid);

File is added correctly but there i no filename so users can not open it without first renaming it.

![image](https://user-images.githubusercontent.com/3002124/101796873-aee63900-3b09-11eb-984d-a6ee7add968c.png)

**Comment by supertosse** [comment]
I'm not able to reproduce this. The filename is taken from the file you send in, and there is a validation on empty filenames, so I don't see how this is possible. Is there any more information you are able to give me about this? Are you sending in a file called no_file_name_provided?

**Comment by tadrian** [comment]
I am using c# so I was using the AttachAsync method in this library (see below) , and it did not have filename in the signature.
is this not correct?, is there a better librarary to use?

https://github.com/foretagsplatsen/tripletex/blob/master/tripletex/src/TripletexAPILibrary/Api/OrderApi.cs

**Comment by tlxtellef** [comment]
That filename is from [here](https://github.com/foretagsplatsen/tripletex/blob/196777e1aaf74db9a2d471239634e47a46158c27/tripletex/src/TripletexAPILibrary/Client/ApiClient.cs#L232), meaning what you need to do use a `FileStream`. This has nothing to do with out API, but with a client library someone else have made.

**Comment by tadrian** [comment]
it is a client library genererated from your swagger json.
can you please point me to a solution?

**Comment by ergor** [comment]
`stream` must specifically be of type `FileStream`. Anything else will result in  "no_file_name_provided".
Please check that you're giving it a `FileStream` and not any other subclass of `Stream`.

**Comment by tadrian** [comment]
I resolved it, thanks
