### ISSUE TITLE
Test API registration form broken?

### ISSUE THREAD

**Issue by mmrko** [Tripletex/tripletex-api2#30]
Trying to register a new Tripletex account for testing the API (our previous one expired) via https://api.tripletex.io. When submitting the form, an error is returned: _Ugyldig telefonnummer_. Tried also with a valid Norwegian mobile telephone number but no cigar. Doubt that the phone number is the issue, could the error message be wrong? Would appreciate a quick resolution to the issue. Thanks! :)

**Comment by MagnusGund** [comment]
Hello,

We do validate for a valid norwegian phone number. I just tried the registration with my mobile number and it seems to work fine. Are you sure you entered a valid one?

**Comment by mmrko** [comment]
OK, worked now with a different one. I must've typoed it the first time around. Thanks for the help! :)
