### ISSUE TITLE
Unable to create orderLines embedded in orderobject via POST to /order

### ISSUE THREAD

**Issue by onklmaps** [Tripletex/tripletex-api2#32]
When I create an invoice with `POST /invoice`, I can embed an order-object that has an array of orderLine-objects embedded. The result is that an Invoice, an order and the orderlines are created with one API-call.

The same should be possible with `POST /order`

**Comment by supertosse** [comment]
This is noted and will be fixed when we have time for it

**Comment by b-brodie** [comment]
Any update on whether this is fixed? Or should we use the new `POST /order/list` endpoint for this purpose instead?

**Comment by ergor** [comment]
Hi, I am working on this feature now. I will keep you up to date.

**Comment by neburx** [comment]
A fix for this is now deployed

**Comment by onklmaps** [comment]
Thank you :-)
