### ISSUE TITLE
Unable to (re)send EHF invoice

### ISSUE THREAD

**Issue by mmrko** [Tripletex/tripletex-api2#33]
Hi,

I'm using `PUT /v2/invoice/123456789/:send?sendType=EHF` to send a reminder on a previously sent (created) invoice. The request seems to fail with the following error payload:

```js
{
  status: 500,
  code: 1002,
  message: 'ApplicationException',
  link: 'https://www.tripletex.no/tripletex-api-2-0/',
  developerMessage: null,
  validationMessages: null,
  requestId: '6a15197e-7af5-4cf0-a101-cef71a1b9c64'
}
```

Changing `sendType` to e.g. `EMAIL` fixes this but isn't of course ideal.

**Comment by ergor** [comment]
Hi, 

This is a bug. I found what causes it and will create a task. I'll keep you updated.

**Comment by ergor** [comment]
Hi,

A fix for this has been deployed. Please notify if for some reason the issue prevails
