### ISSUE TITLE
Getting token date requires expiration in the past

### ISSUE THREAD

**Issue by frankhaugen** [Tripletex/tripletex-api2#36]
Number two and five works
![image](https://user-images.githubusercontent.com/13543585/116513585-1c80df00-a8ca-11eb-9039-ea0c7e7b920c.png)

That makes no sense! Bug or feature?

(Also Year-Day-Month is not ISO)

**Comment by tlxtellef** [comment]
You are correct that formats such as `YYYY-dd-MM` isn't ISO 8601.

We only support ISO 8601. If you had read the [API documentation](https://tripletex.no/v2-docs/) you would have known that.
![image](https://user-images.githubusercontent.com/28530080/116516187-95356a80-a8cd-11eb-89cd-b9671cfa5f4d.png)

**Comment by frankhaugen** [comment]
@tlxtellef Sorry, I am working with code made by consultants, so they had said that this was a strange situation, and I had no reason to question them. My bad
