### ISSUE TITLE
Swagger codegen runs out of memory

### ISSUE THREAD

**Issue by alexhost** [Tripletex/tripletex-api2#37]
Attempting to generate C# code from Swagger spec runs out of memory.

Running with jdk1.8.0_291, max heap size 4gb.

A bit strange as the log suggests this is occurring on an markdown file.

![image](https://user-images.githubusercontent.com/14944283/118017376-d52d3080-b356-11eb-9d81-5b20b0a72dfa.png)

**Comment by tlxtellef** [comment]
The error you are encountering is a known issue with Swagger-Codegen.
See for example [swagger-codegen#10199](https://github.com/swagger-api/swagger-codegen/issues/10199) (that I opened regarding this last year regarding this)

The only quick solution that exists currently is allocating more memory for generating, this also means that you will need a 64bit computer with more than 4GB of ram to generate the client.

Alternatively one could fork and just disable the example json-pregen code of the generator, as it isn't used for anything important anyways.

**Comment by alexhost** [comment]
For future reference, I managed to get the job done with the following, but I needed 24gb of memory. 20gb was not enough.

`java -d64 -Xmx24g -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://tripletex.no/v2/swagger.json -l csharp -o d:\tripletex`
