### ISSUE TITLE
GET inventory/inventories returns inventory with name and no ID

### ISSUE THREAD

**Issue by onklmaps** [Tripletex/tripletex-api2#38]
When querying `inventory/inventories` you get a response with the name of the _inventory_(warehouse), and no ID.

**Example response today (part of it):**

                "stock": [
                {
                    "inventory": "Hovedlager",
                    "openingStock": 0,
                    "changesInPeriod": 0,
                    "closingStock": 0
                },
                {
                    "inventory": "Kasserte-varer",
                    "openingStock": 0,
                    "changesInPeriod": 0,
                    "closingStock": 0
                },
            ]

**Should be something like:**

                "stock": [
                {
                    "inventory": [{
                           "inventoryId": 123,
                           "name": "Hovedlager",
                     }],
                    "openingStock": 0,
                    "changesInPeriod": 0,
                    "closingStock": 0
                },
                {
                    "inventory": [{
                           "inventoryId": 234,
                           "name": "Kasserte varer",
                     }],
                    "openingStock": 0,
                    "changesInPeriod": 0,
                    "closingStock": 0
                },
            ]

**Comment by florinfometescu** [comment]
We can't change (at least for the moment) the structure of the object because we are using this structure in other places and requires a lot of time and testing to change everywhere. Also not sure why is needed array of objects  [ ]
              "inventory": [{
                       "inventoryId": 123,
                       "name": "Hovedlager",
                 }],
there is only 1 inventory with name and id.

I have an other proposal of the structure to send the required field. This solution can be implemented faster.

   "stock": [
            {
                "inventory": "Hovedlager",
                "inventoryId": 256,
                "openingStock": 0,
                "changesInPeriod": 0,
                "closingStock": 0
            }
        ]

Please let me know if we can proceed with solution.

Kind Regards,
Florin

**Comment by onklmaps** [comment]
@florinfometescu Your proposed structure looks perfect 👍
Thank you

**Comment by florinfometescu** [comment]
Hello, 

Should work in production the new structure. Let me know if there is anything else i can do.

Kind Regards,
Florin
