### ISSUE TITLE
Using inventoryId as query parameter for GET inventory/inventories does no difference

### ISSUE THREAD

**Issue by onklmaps** [Tripletex/tripletex-api2#39]
When I run `GET inventory/inventories?inventoryId=123` I get the exact same response as when I run `GET inventory/inventories` without that parameter.

I would expect to only get results for warehouse/inventory with id 123.

**Comment by itvedte** [comment]
Hi,
The response should now return only results for the specified warehouse/inventory from the query. 
Regards,
Ingvild
