### ISSUE TITLE
Birds Eye: Creating a new session: 

### ISSUE THREAD

**Issue by klatremus** [Tripletex/tripletex-api2#53]
***Disclaimer: I might have asked this question in the wrong fora, ie, hope you may forgive me***

Problem: When using the tripltex Python API, the following error (on session-creation) is received:
```json
 ERROR: 422 {
  "status" : 422,
  "code" : 18000,
  "message" : "Validering feilet.",
  "link" : "https://www.tripletex.no/tripletex-api-2-0/",
  "developerMessage" : null,
  "validationMessages" : [ {
    "field" : "arg:consumerToken",
    "message" : "The consumer token is invalid or does not exist.",
    "path" : "arg:consumerToken",
    "rootId" : null
  } ],
  "requestId" : "e7563c66-b243-440a-a4a0-278fda002eba"
} 
```

The Consumer Token:
- was received by email from the TripleTex help-desk

Question:
- how to resolve this issue?

Cheers,

@klatremus

**Comment by tlxtellef** [comment]
Looking at the logs it seems the issue here is most likely that you used the production consumer tokens in our staging environment. [https://tripletex.no](https://tripletex.no) and [https://api.tripletex.io](https://api.tripletex.io) are separate environments with completely separate tokens. Setting up and getting tokens for said staging environment can be done via the [self service page](https://api.tripletex.io/execute/integrationEnvironment?site=en)

**Comment by klatremus** [comment]
>  Setting up and getting tokens for said the staging environment can be done via the [self service page](https://api.tripletex.io/execute/integrationEnvironment?site=en)

Thanks for your reply!
- however, the link (you provides) points to a registering Page: as I'm already registered, I'm not allowed to proceed, ie, the link sadly did not help (;. 

_Thus, I have tried finding a "customer token" configurations-tab, which I've been unable to._

**Question**
- do you have an URL to where setting the "customer token"?


Often, examples help:
![image](https://user-images.githubusercontent.com/25556837/149905379-4f2fb39a-9764-4432-8aad-3d93bae7bbcf.png)

From the above screen-shot:
- while I do have the rights to set the "production token", it seems like I do not have the (??) access-privileges (to set the customer token): correct?
- suggestions for the page/tab to use (for setting the customer token)?

**Comment by tlxtellef** [comment]
Do NOT post token here, this is a public forum. Go email support instead if you want to resolve such issues.
