### ISSUE TITLE
PUT/order/{id}/:invoice 

### ISSUE THREAD

**Issue by GroHVD** [Tripletex/tripletex-api2#65]
Hi,

When we make a post / order on an order that already exists in Tripletex, it will not be possible to create a new order with the same number. We were told by you to create a new invoice on existing orders, and that we could do it via PUT / order / {id} /: invoice. 
We have now tested "PUT / order / {id} /: invoice" that you advised us, but the difference is that the new method doesn’t support us setting Invoice No. or Due Date. Do you have  a solution to set them?

Best regards Gro
Håndverksdata

**Comment by neburx** [comment]
Hi, 

A little unclear what you try to do here. "POST invoice" would allow you to set both invoice number and duedate when creating a new invoice from an order. This will then invoice the orderlines but not close the order. You could then close the order with "PUT order" or add new orderlines to continue using it.

The "PUT / order / {id} /: invoice" endpoint would close the order and invoice the orderlines. No other update is done to the order. The invoice number must be unique and sequential and will  be generated from the system thus not possible to set this. Due date is not a field in order and is a calculation of invoicedate + the number of due days/months on the order.

**Comment by GroHVD** [comment]
Hi,
The customers invoice the orders in our system, so when we send the invoices to Tripletex, the order number and the invoice number already exist. When the customers invoice the entire order at once,  they have had no problem using post / order, but if the customers create an aconto invoice and then invoice the entire order, they get an error message because the order number already exists in Tripletex.
We were told by you that it would be more correct to create a new invoice on exsisting orders by using "PUT / order / {id} /: invoice", but then we are not able to send you the invoice number or due date.
What we want to do is to send you several invoices with different invoice numbers,  but with the same order number. Is is possible?

**Comment by GroHVD** [comment]
Hi,

What about partial invoicing?

Gro Fosskaug
Product Owner/

Mobil: +47 90071088
***@***.******@***.***>

***@***.***

Fra: Ruben Aarø ***@***.***>
Sendt: fredag 16. september 2022 14:32
Til: Tripletex/tripletex-api2 ***@***.***>
Kopi: Gro H. Fosskaug ***@***.***>; Author ***@***.***>
Emne: Re: [Tripletex/tripletex-api2] PUT/order/{id}/:invoice (Issue #65)


Hi,

Unfortunately we do not support using your own invoice number when invoicing on the same order multiple times ("PUT / order / {id} /: invoice")

Currently the only solution we think could work would be to create a new order with an orderline that subtracts the previously invoiced aconto amount and have the remaining orderlines to be invoiced, and then invoice it through "POST invoice" with your own invoice number.

**Comment by GroHVD** [comment]
Hei,

Takk for tilbakemeldingen. Fint om jeg kan få beskjed dersom dette blir utviklet.

Mvh Gro

Få Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neburx** [comment]
We will inform if/when this is developed
