### ISSUE TITLE
[BUG] OpenAPI client validation fails cause response returns a larger string than what is defined in swagger.json

### ISSUE THREAD

**Issue by Nicolai-** [Tripletex/tripletex-api2#70]
Hi,

We are having an issue where the definition says the max length of the `displayName` on the `Address` is 100, but the API returns a response with a `displayName` of 120 characters, which means the client built on the definition cannot decode the response and throws an exception

It is the `postalAddress` and `physicalAddress` on `Supplier` object

**Comment by tlxtellef** [comment]
That is a bug indeed, that field is actually read-only. What had happened is that a validation rule had been placed on it by mistake.

**Comment by tlxtellef** [comment]
This issue should be resolved now, a fix for this was deployed yesterday.
