### ISSUE TITLE
Unable to update voucher number using PUT /ledger/voucher/{}     

### ISSUE THREAD

**Issue by kidisy** [Tripletex/tripletex-api2#88]
I want to update the voucher by sending new file or resend the previous data by using PUT
"/ledger/voucher/{}".format(self.api, id)
        payload = {"number": id}
then i get this error message 
 "status" : 422,
  "code" : 18000,
  "message" : "Validering feilet.",
  "link" : "https://www.tripletex.no/tripletex-api-2-0/",
  "developerMessage" : "VALIDATION_ERROR",
  "validationMessages" : [ {
    "field" : "null",
    "message" : "Errors:\r\nBilagsnummer *******-2023 er allerede registrert."
    "path" : "null",
    "rootId" : "null"
  } ],
  "requestId" : "*******-****-****-****-***********"
Any suggestion how i use the previous voucher number with the new sent data?

**Comment by tlxVidar** [comment]
The voucher number is a system generated number that cannot be changed.
In general the voucher number is generated by the system when the voucher is sent to the ledger, this can be done both on POST and on PUT, this is controlled with the parameter "sendToLedger"

**Comment by kidisy** [comment]
ok, thank you
